-- ==============================================================================
-- PART 3: DATABASE QUERYING & OPTIMIZATION (10 Business Queries)
-- RDBMS: Microsoft SQL Server (SSMS) / T-SQL
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- REQUIREMENT 1: MULTI-TABLE JOINS (Minimum 3 Queries)
-- ------------------------------------------------------------------------------

-- Query 1: INNER JOIN (4 Tables)
-- Business Question: "Generate a comprehensive list of all active rentals, showing the customer name, the staff member who processed it, and the branch location."
SELECT 
    r.RentalID,
    c.Name AS CustomerName,
    s.Name AS ProcessedBy_Agent,
    b.Name AS BranchLocation,
    r.RentalDate
FROM Rental r
INNER JOIN Customer c ON r.CustomerID = c.CustomerID
INNER JOIN Staff s ON r.StaffID = s.StaffID
INNER JOIN Branch b ON s.BranchID = b.BranchID
WHERE r.Status = 'Active';

-- Query 2: LEFT JOIN 
-- Business Question: "Review our vehicle catalog to see which vehicle types we currently have in our fleet, including vehicle types we offer but currently have zero cars for (e.g., Cargo Vans)."
SELECT 
    vt.TypeName,
    vt.SeatingCapacity,
    c.Model,
    c.RegistrationNumber
FROM Vehicle_Type vt
LEFT JOIN Car c ON vt.VehicleTypeID = c.VehicleTypeID
ORDER BY vt.TypeName;

-- Query 3: INNER JOIN (Targeting Sub-types)
-- Business Question: "Create a direct contact directory specifically for our Corporate clients, including their phone numbers and Tax IDs."
SELECT 
    corp.CompanyName,
    corp.TaxID,
    c.Email,
    cp.PhoneNumber
FROM Corporate corp
INNER JOIN Customer c ON corp.CustomerID = c.CustomerID
INNER JOIN Customer_Phone cp ON c.CustomerID = cp.CustomerID;

-- ------------------------------------------------------------------------------
-- REQUIREMENT 2: DATA AGGREGATION WITH GROUP BY & HAVING (Minimum 2 Queries)
-- ------------------------------------------------------------------------------

-- Query 4: SUM, GROUP BY, HAVING
-- Business Question: "Calculate the total revenue generated by each branch, but only display the top-performing branches that have generated more than $300 in total payments."
SELECT 
    b.Name AS BranchName,
    SUM(p.Amount) AS TotalRevenue
FROM Branch b
INNER JOIN Staff s ON b.BranchID = s.BranchID
INNER JOIN Rental r ON s.StaffID = r.StaffID
INNER JOIN Payment p ON r.RentalID = p.RentalID
GROUP BY b.Name
HAVING SUM(p.Amount) > 300;

-- Query 5: AVG, COUNT, GROUP BY, HAVING
-- Business Question: "What is the average daily rental rate for each vehicle type? Only show vehicle types where we own at least 2 cars of that type."
SELECT 
    vt.TypeName,
    COUNT(c.CarID) AS NumberOfCarsOwned,
    AVG(c.DailyRate) AS AverageDailyRate
FROM Vehicle_Type vt
INNER JOIN Car c ON vt.VehicleTypeID = c.VehicleTypeID
GROUP BY vt.TypeName
HAVING COUNT(c.CarID) >= 2;

-- ------------------------------------------------------------------------------
-- REQUIREMENT 3: SUBQUERIES (Minimum 2 Queries)
-- ------------------------------------------------------------------------------

-- Query 6: Subquery using IN
-- Business Question: "Identify all customers who have rented premium/large vehicles (Luxury Sedans or Full-Size SUVs) so we can target them for an upcoming VIP promotion."
SELECT 
    Name AS VIP_Customer,
    Email
FROM Customer
WHERE CustomerID IN (
    SELECT r.CustomerID 
    FROM Rental r
    INNER JOIN Rental_Car rc ON r.RentalID = rc.RentalID
    INNER JOIN Car c ON rc.CarID = c.CarID
    INNER JOIN Vehicle_Type vt ON c.VehicleTypeID = vt.VehicleTypeID
    WHERE vt.TypeName IN ('Luxury Sedan', 'Full-Size SUV')
);

-- Query 7: Scalar Subquery
-- Business Question: "List the specific car models and their daily rates that are priced higher than the overall average daily rate of our entire fleet."
SELECT 
    Model,
    RegistrationNumber,
    DailyRate
FROM Car
WHERE DailyRate > (
    SELECT AVG(DailyRate) 
    FROM Car
);

-- Query 8: Subquery using EXISTS
-- Business Question: "Which branches currently have cars undergoing maintenance? (This helps logistics know which branches might be short on inventory)."
SELECT 
    Name AS Branches_With_Cars_In_Shop
FROM Branch b
WHERE EXISTS (
    SELECT 1 
    FROM Car c 
    WHERE c.BranchID = b.BranchID 
    AND c.Status = 'Maintenance'
);

-- ------------------------------------------------------------------------------
-- REQUIREMENT 4: ADDITIONAL BUSINESS QUERIES (To meet the 10 total minimum)
-- ------------------------------------------------------------------------------

-- Query 9: Date Functions & Filtering
-- Business Question: "Which vehicle insurance policies are expiring in the year 2026 and need to be flagged for renewal by the fleet manager?"
SELECT 
    ip.Provider,
    c.Model,
    c.RegistrationNumber,
    ip.ExpiryDate,
    ip.CoverageAmount
FROM Insurance_Policy ip
INNER JOIN Car c ON ip.CarID = c.CarID
WHERE YEAR(ip.ExpiryDate) = 2026
ORDER BY ip.ExpiryDate ASC;

-- Query 10: MAX / Complex Analytics
-- Business Question: "What was the single largest payment amount we have received, and which rental transaction and customer was it associated with?"
SELECT TOP 1
    p.Amount AS LargestPayment,
    p.PaymentDate,
    p.PaymentMethod,
    c.Name AS CustomerName,
    r.RentalID
FROM Payment p
INNER JOIN Rental r ON p.RentalID = r.RentalID
INNER JOIN Customer c ON r.CustomerID = c.CustomerID
ORDER BY p.Amount DESC;

-- ==============================================================================
-- MUST ADD THIS 'GO' STATEMENT HERE
-- ==============================================================================
GO 

-- ==============================================================================
-- ADVANCED OBJECT 1: DATABASE VIEW
-- Business Use: Simplifies a 5-table join to instantly view all active rentals.
-- ==============================================================================

CREATE VIEW vw_ActiveRentalDetails AS
SELECT 
    r.RentalID,
    c.Name AS CustomerName,
    c.Email,
    car.Model,
    car.RegistrationNumber,
    r.RentalDate,
    r.ReturnDate,
    s.Name AS ProcessedBy_Agent
FROM Rental r
INNER JOIN Customer c ON r.CustomerID = c.CustomerID
INNER JOIN Rental_Car rc ON r.RentalID = rc.RentalID
INNER JOIN Car car ON rc.CarID = car.CarID
INNER JOIN Staff s ON r.StaffID = s.StaffID
WHERE r.Status = 'Active';

-- ==============================================================================
-- MUST ADD ANOTHER 'GO' STATEMENT HERE
-- ==============================================================================
GO

-- ==============================================================================
-- ADVANCED OBJECT 2: DATABASE TRIGGER
-- Business Use: Automates fleet inventory management by updating car status.
-- ==============================================================================

CREATE TRIGGER trg_UpdateCarStatusOnRental
ON Rental_Car
AFTER INSERT
AS
BEGIN
    UPDATE Car
    SET Status = 'Rented'
    WHERE CarID IN (SELECT CarID FROM inserted);
    
    PRINT 'Trigger Executed: Car status automatically updated to Rented.';
END;
GO